[tool.poetry]
name = "1on1questions"
version = "0.1.0"
description = ""
authors = ["Noam Elfanbaum <noam.elf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.0"
flask = "^1.1.1"
gunicorn = "^20.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
